/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "k8s-operator/operator/reboot/pkg/apis/reboot/v1alpha1"
	scheme "k8s-operator/operator/reboot/pkg/client/clientset/versioned/scheme"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// RebootsGetter has a method to return a RebootInterface.
// A group's client should implement this interface.
type RebootsGetter interface {
	Reboots(namespace string) RebootInterface
}

// RebootInterface has methods to work with Reboot resources.
type RebootInterface interface {
	Create(*v1alpha1.Reboot) (*v1alpha1.Reboot, error)
	Update(*v1alpha1.Reboot) (*v1alpha1.Reboot, error)
	UpdateStatus(*v1alpha1.Reboot) (*v1alpha1.Reboot, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.Reboot, error)
	List(opts v1.ListOptions) (*v1alpha1.RebootList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Reboot, err error)
	RebootExpansion
}

// reboots implements RebootInterface
type reboots struct {
	client rest.Interface
	ns     string
}

// newReboots returns a Reboots
func newReboots(c *RebootV1alpha1Client, namespace string) *reboots {
	return &reboots{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the reboot, and returns the corresponding reboot object, and an error if there is any.
func (c *reboots) Get(name string, options v1.GetOptions) (result *v1alpha1.Reboot, err error) {
	result = &v1alpha1.Reboot{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("reboots").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Reboots that match those selectors.
func (c *reboots) List(opts v1.ListOptions) (result *v1alpha1.RebootList, err error) {
	result = &v1alpha1.RebootList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("reboots").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested reboots.
func (c *reboots) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("reboots").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a reboot and creates it.  Returns the server's representation of the reboot, and an error, if there is any.
func (c *reboots) Create(reboot *v1alpha1.Reboot) (result *v1alpha1.Reboot, err error) {
	result = &v1alpha1.Reboot{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("reboots").
		Body(reboot).
		Do().
		Into(result)
	return
}

// Update takes the representation of a reboot and updates it. Returns the server's representation of the reboot, and an error, if there is any.
func (c *reboots) Update(reboot *v1alpha1.Reboot) (result *v1alpha1.Reboot, err error) {
	result = &v1alpha1.Reboot{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("reboots").
		Name(reboot.Name).
		Body(reboot).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *reboots) UpdateStatus(reboot *v1alpha1.Reboot) (result *v1alpha1.Reboot, err error) {
	result = &v1alpha1.Reboot{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("reboots").
		Name(reboot.Name).
		SubResource("status").
		Body(reboot).
		Do().
		Into(result)
	return
}

// Delete takes name of the reboot and deletes it. Returns an error if one occurs.
func (c *reboots) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("reboots").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *reboots) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("reboots").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched reboot.
func (c *reboots) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Reboot, err error) {
	result = &v1alpha1.Reboot{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("reboots").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
