/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	v1 "k8s-operator/operator/reboot/pkg/apis/reboot/v1"
	scheme "k8s-operator/operator/reboot/pkg/client/clientset/versioned/scheme"

	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// RebootOperatorsGetter has a method to return a RebootOperatorInterface.
// A group's client should implement this interface.
type RebootOperatorsGetter interface {
	RebootOperators(namespace string) RebootOperatorInterface
}

// RebootOperatorInterface has methods to work with RebootOperator resources.
type RebootOperatorInterface interface {
	Create(*v1.RebootOperator) (*v1.RebootOperator, error)
	Update(*v1.RebootOperator) (*v1.RebootOperator, error)
	UpdateStatus(*v1.RebootOperator) (*v1.RebootOperator, error)
	Delete(name string, options *meta_v1.DeleteOptions) error
	DeleteCollection(options *meta_v1.DeleteOptions, listOptions meta_v1.ListOptions) error
	Get(name string, options meta_v1.GetOptions) (*v1.RebootOperator, error)
	List(opts meta_v1.ListOptions) (*v1.RebootOperatorList, error)
	Watch(opts meta_v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.RebootOperator, err error)
	RebootOperatorExpansion
}

// rebootOperators implements RebootOperatorInterface
type rebootOperators struct {
	client rest.Interface
	ns     string
}

// newRebootOperators returns a RebootOperators
func newRebootOperators(c *RebootV1Client, namespace string) *rebootOperators {
	return &rebootOperators{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the rebootOperator, and returns the corresponding rebootOperator object, and an error if there is any.
func (c *rebootOperators) Get(name string, options meta_v1.GetOptions) (result *v1.RebootOperator, err error) {
	result = &v1.RebootOperator{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("rebootoperators").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of RebootOperators that match those selectors.
func (c *rebootOperators) List(opts meta_v1.ListOptions) (result *v1.RebootOperatorList, err error) {
	result = &v1.RebootOperatorList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("rebootoperators").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested rebootOperators.
func (c *rebootOperators) Watch(opts meta_v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("rebootoperators").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a rebootOperator and creates it.  Returns the server's representation of the rebootOperator, and an error, if there is any.
func (c *rebootOperators) Create(rebootOperator *v1.RebootOperator) (result *v1.RebootOperator, err error) {
	result = &v1.RebootOperator{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("rebootoperators").
		Body(rebootOperator).
		Do().
		Into(result)
	return
}

// Update takes the representation of a rebootOperator and updates it. Returns the server's representation of the rebootOperator, and an error, if there is any.
func (c *rebootOperators) Update(rebootOperator *v1.RebootOperator) (result *v1.RebootOperator, err error) {
	result = &v1.RebootOperator{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("rebootoperators").
		Name(rebootOperator.Name).
		Body(rebootOperator).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *rebootOperators) UpdateStatus(rebootOperator *v1.RebootOperator) (result *v1.RebootOperator, err error) {
	result = &v1.RebootOperator{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("rebootoperators").
		Name(rebootOperator.Name).
		SubResource("status").
		Body(rebootOperator).
		Do().
		Into(result)
	return
}

// Delete takes name of the rebootOperator and deletes it. Returns an error if one occurs.
func (c *rebootOperators) Delete(name string, options *meta_v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("rebootoperators").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *rebootOperators) DeleteCollection(options *meta_v1.DeleteOptions, listOptions meta_v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("rebootoperators").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched rebootOperator.
func (c *rebootOperators) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.RebootOperator, err error) {
	result = &v1.RebootOperator{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("rebootoperators").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
