/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	reboot_v1 "k8s-operator/operator/reboot/pkg/apis/reboot/v1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeRebootOperators implements RebootOperatorInterface
type FakeRebootOperators struct {
	Fake *FakeRebootV1
	ns   string
}

var rebootoperatorsResource = schema.GroupVersionResource{Group: "reboot", Version: "v1", Resource: "rebootoperators"}

var rebootoperatorsKind = schema.GroupVersionKind{Group: "reboot", Version: "v1", Kind: "RebootOperator"}

// Get takes name of the rebootOperator, and returns the corresponding rebootOperator object, and an error if there is any.
func (c *FakeRebootOperators) Get(name string, options v1.GetOptions) (result *reboot_v1.RebootOperator, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(rebootoperatorsResource, c.ns, name), &reboot_v1.RebootOperator{})

	if obj == nil {
		return nil, err
	}
	return obj.(*reboot_v1.RebootOperator), err
}

// List takes label and field selectors, and returns the list of RebootOperators that match those selectors.
func (c *FakeRebootOperators) List(opts v1.ListOptions) (result *reboot_v1.RebootOperatorList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(rebootoperatorsResource, rebootoperatorsKind, c.ns, opts), &reboot_v1.RebootOperatorList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &reboot_v1.RebootOperatorList{}
	for _, item := range obj.(*reboot_v1.RebootOperatorList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested rebootOperators.
func (c *FakeRebootOperators) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(rebootoperatorsResource, c.ns, opts))

}

// Create takes the representation of a rebootOperator and creates it.  Returns the server's representation of the rebootOperator, and an error, if there is any.
func (c *FakeRebootOperators) Create(rebootOperator *reboot_v1.RebootOperator) (result *reboot_v1.RebootOperator, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(rebootoperatorsResource, c.ns, rebootOperator), &reboot_v1.RebootOperator{})

	if obj == nil {
		return nil, err
	}
	return obj.(*reboot_v1.RebootOperator), err
}

// Update takes the representation of a rebootOperator and updates it. Returns the server's representation of the rebootOperator, and an error, if there is any.
func (c *FakeRebootOperators) Update(rebootOperator *reboot_v1.RebootOperator) (result *reboot_v1.RebootOperator, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(rebootoperatorsResource, c.ns, rebootOperator), &reboot_v1.RebootOperator{})

	if obj == nil {
		return nil, err
	}
	return obj.(*reboot_v1.RebootOperator), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeRebootOperators) UpdateStatus(rebootOperator *reboot_v1.RebootOperator) (*reboot_v1.RebootOperator, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(rebootoperatorsResource, "status", c.ns, rebootOperator), &reboot_v1.RebootOperator{})

	if obj == nil {
		return nil, err
	}
	return obj.(*reboot_v1.RebootOperator), err
}

// Delete takes name of the rebootOperator and deletes it. Returns an error if one occurs.
func (c *FakeRebootOperators) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(rebootoperatorsResource, c.ns, name), &reboot_v1.RebootOperator{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeRebootOperators) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(rebootoperatorsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &reboot_v1.RebootOperatorList{})
	return err
}

// Patch applies the patch and returns the patched rebootOperator.
func (c *FakeRebootOperators) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *reboot_v1.RebootOperator, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(rebootoperatorsResource, c.ns, name, data, subresources...), &reboot_v1.RebootOperator{})

	if obj == nil {
		return nil, err
	}
	return obj.(*reboot_v1.RebootOperator), err
}
