/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	patch_v1 "k8s-operator/operator/patch/pkg/apis/patch/v1"
	versioned "k8s-operator/operator/patch/pkg/client/clientset/versioned"
	internalinterfaces "k8s-operator/operator/patch/pkg/client/informers/externalversions/internalinterfaces"
	v1 "k8s-operator/operator/patch/pkg/client/listers/patch/v1"
	time "time"

	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// PatchOperatorInformer provides access to a shared informer and lister for
// PatchOperators.
type PatchOperatorInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.PatchOperatorLister
}

type patchOperatorInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewPatchOperatorInformer constructs a new informer for PatchOperator type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewPatchOperatorInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredPatchOperatorInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredPatchOperatorInformer constructs a new informer for PatchOperator type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredPatchOperatorInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options meta_v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.PatchV1().PatchOperators(namespace).List(options)
			},
			WatchFunc: func(options meta_v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.PatchV1().PatchOperators(namespace).Watch(options)
			},
		},
		&patch_v1.PatchOperator{},
		resyncPeriod,
		indexers,
	)
}

func (f *patchOperatorInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredPatchOperatorInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *patchOperatorInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&patch_v1.PatchOperator{}, f.defaultInformer)
}

func (f *patchOperatorInformer) Lister() v1.PatchOperatorLister {
	return v1.NewPatchOperatorLister(f.Informer().GetIndexer())
}
